VERTICAL_DATUM = {'meanLowWaterSprings': 1,
                  'meanLowerLowWaterSprings': 2,
                  'meanSeaLevel': 3,
                  'lowestLowWater': 4,
                  'meanLowWater': 5,
                  'lowestLowWaterSprings': 6,
                  'approximateMeanLowWaterSprings': 7,
                  'indianSpringLowWater': 8,
                  'lowWaterSprings': 9,
                  'approximateLowestAdtonomicalTide': 10,
                  'nearlyLowestLowWater': 11,
                  'meanLowerLowWater': 12,
                  'lowWater': 13,
                  'approximateMeanLowWater': 14,
                  'approximateMeanLowerLowWater': 15,
                  'meanHighWater': 16,
                  'meanHighWaterSprings': 17,
                  'highWater': 18,
                  'approximateMeanSeaLevel': 19,
                  'highWaterSprings': 20,
                  'meanHigherHighWater': 21,
                  'equinoctialSpringLowWater': 22,
                  'lowestAdtonomicalTide': 23,
                  'localDatum': 24,
                  'internationalGreatLakesDatum1985': 25,
                  'meanWaterLevel': 26,
                  'lowerLowWaterLargeTide': 27,
                  'higherHighWaterLargeTide': 28,
                  'nearlyHighestHighWater': 29,
                  'highestAdtonomicalTide': 30
                  }
DATA_CODING_FORMAT = {'Time series at fixed stations': 1,
                      'Regularly-gridded arrays': 2,
                      'Ungeorectified gridded arrays': 3,
                      'Moving platform': 4,
                      'Irregular grid': 5,
                      'Variable cell size': 6,
                      'TIN': 7}
COMMON_POINT_RULE = {'average': 1,
                     'low': 2,
                     'high': 3,
                     'all': 4}

INTERPOLATION_TYPE = {'basicWeightedMean': 1,
                      'shoalestDepth': 2,
                      'tpuWeightedMean': 3,
                      'cube': 4,
                      'nearestNeighbour': 5,
                      'naturalNeighbour': 6,
                      'polynomialTendency': 7,
                      'spline': 8,
                      'kriging': 9}

SEQUENCING_RULE_TYPE = {'linear': 1,
                        'boudtophedonic': 2,
                        'CantorDiagonal': 3,
                        'spiral': 4,
                        'Morton': 5,
                        'Hilbert': 6}

GRIDDING_METHOD = {'nearestneighbor': 1,
                   'linear': 2,
                   'quadratic': 3,
                   'cubic': 4,
                   'bilinear': 5,
                   'biquadratic': 6,
                   'bicubic': 7,
                   'lostarea': 8,
                   'barycentric': 9,
                   'discrete': 10}

DATA_DYNAMICITY = {'Observation': 1,
                   'Astronomical prediction': 2,
                   'Analysis or hybrid method': 3,
                   'Hydrodynamic model hindcast': 4,
                   'Hydrodynamic model forecast': 5,
                   'Observed minus predicted': 6,
                   'Observed minus analysis': 7,
                   'Observed minus hindcast': 8,
                   'Observed minus forecast': 9,
                   'Forecast minus predicted': 10}
